# Generated by Django 5.1.1 on 2025-01-25 03:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_vendidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('asistencia_ID', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Justificada', 'Justificada'), ('Ausente', 'Ausente')], max_length=11)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Justificaciones',
            fields=[
                ('justificacion_ID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Pendiente', 'Pendiente'), ('Denegada', 'Denegada')], max_length=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('puesto_ID', models.AutoField(primary_key=True, serialize=False)),
                ('puesto_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_ID', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Vendidos',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='users_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='rol',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='users',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener entre 8 y 10 dígitos.', regex='^\\d{8,10}$')], verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='users',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='justificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.justificaciones'),
        ),
        migrations.AddField(
            model_name='users',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.puestos'),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.roles'),
        ),
    ]
