# Generated by Django 5.1.4 on 2025-01-25 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_asistencia_fecha_alter_asistencia_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_ID', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('jornada_ID', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, choices=[('Aprobada', 'Aprobada'), ('Pendiente', 'Pendiente'), ('Denegada', 'Denegada')], max_length=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('justificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.justificaciones')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Descansos',
            fields=[
                ('descanso_ID', models.AutoField(primary_key=True, serialize=False)),
                ('descanso_inicio', models.DateTimeField(blank=True, null=True)),
                ('descanso_fin', models.DateTimeField(blank=True, null=True)),
                ('descanso_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jornada')),
            ],
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
