# Generated by Django 5.1.4 on 2025-01-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_roles_jornada_descansos_delete_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='descansos',
            name='descanso_fin',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='descansos',
            name='descanso_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
