# Generated by Django 5.1.4 on 2025-01-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_users_estado_alter_descansos_descanso_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descansos',
            name='descanso_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
