# Generated by Django 5.1.4 on 2025-01-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_descansos_descanso_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificaciones',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='justificaciones',
            name='fecha_inicial',
        ),
        migrations.AlterField(
            model_name='descansos',
            name='descanso_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='estado',
            field=models.CharField(choices=[('Aprobada', 'Aprobada'), ('Pendiente', 'Pendiente'), ('Denegada', 'Denegada')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_inicio',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
