# Generated by Django 5.1.4 on 2025-01-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_descansos_descanso_inicio'),
        ('api', '0039_alter_descansos_descanso_total_and_more'),
    ]

    operations = [
    ]
