# Generated by Django 5.1.1 on 2025-01-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_justificaciones_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='estado',
            field=models.CharField(choices=[('Completa', 'Completa'), ('Incompleta', 'Incompleta')], default='Incompleta', max_length=10),
        ),
    ]
