# Generated by Django 5.1.1 on 2025-01-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_merge_20250125_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificaciones',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='justificaciones',
            name='fecha_inicial',
        ),
        migrations.AlterField(
            model_name='descansos',
            name='descanso_fin',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='descansos',
            name='descanso_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
