# Generated by Django 5.1.4 on 2025-01-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_hist_pagos_fecha_desactivado_alter_hist_pagos_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hist_pagos',
            name='estudiante_id',
        ),
        migrations.RemoveField(
            model_name='hist_ingredientes',
            name='users_id',
        ),
        migrations.RemoveField(
            model_name='recetaingredientes',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='recetaingredientes',
            name='receta',
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
        migrations.DeleteModel(
            name='Hist_pagos',
        ),
        migrations.DeleteModel(
            name='Hist_ingredientes',
        ),
        migrations.DeleteModel(
            name='Ingredientes',
        ),
        migrations.DeleteModel(
            name='RecetaIngredientes',
        ),
        migrations.DeleteModel(
            name='Recetas',
        ),
    ]
