# Generated by Django 5.1.1 on 2025-01-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_users_role_users_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
