# Generated by Django 5.1.1 on 2025-01-25 23:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_users_estado_alter_descansos_descanso_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descansos',
            name='descanso_total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='descansos',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jornada'),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='estado',
            field=models.CharField(choices=[('Aprobada', 'Aprobada'), ('Pendiente', 'Pendiente'), ('Denegada', 'Denegada')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_salida',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='justificaciones',
            name='descripcion',
            field=models.CharField(blank=True, default='No hay descripcion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='justificaciones',
            name='estado',
            field=models.CharField(choices=[('Aprobada', 'Aprobada'), ('Pendiente', 'Pendiente'), ('Denegada', 'Denegada')], max_length=10),
        ),
        migrations.AlterField(
            model_name='justificaciones',
            name='fecha_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='justificaciones',
            name='fecha_inicial',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='puesto_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener entre 8 y 10 dígitos.', regex='^\\d{8,10}$')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='users',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.puestos'),
        ),
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles'),
        ),
    ]
